version: "3.4"
services:
    wh-phrase-extractor-service:
        build:
            context: ${WHATWHY_ROOT_DIR}
            dockerfile: ${WH_PHRASE_EXTRACTOR_DOCKER_FILE}
        image: wh-phrase-extractor
        networks:
            - wh-phrase-extractor-network
    corenlp-service:
        build:
            context: ${WHATWHY_ROOT_DIR}
            dockerfile: ${CORE_NLP_SERVER_DOCKER_FILE}
        image: corenlp-server
        networks:
            - wh-phrase-extractor-network
networks:
    wh-phrase-extractor-network:
        driver: bridge
