version: "3"
services:
    corenlp-service:
        image: nlpbox/corenlp:3.8.0
        deploy:
            replicas: 2
            restart_policy:
                condition: any
        ports:
            - 9000:9000
