version: "3"
services:
    giveme5w1h-service:
        build: .
        image: giveme5w1h
        networks:
            - giveme5w1h-network
        ports:
            - 9099:9099
        environment:
            - CORE_NLP_SERVER_HOST=corenlp-service
        deploy:
            replicas: 1
            restart_policy:
                condition: any
    corenlp-service:
        image: nlpbox/corenlp:3.8.0
        networks:
            - giveme5w1h-network
        ports:
            - 9000:9000
        command: java -Xms2g -Xmx3g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer --timeout 15000 --preload "tokenize,ssplit,pos,lemma,parse,ner,depparse,mention,coref"
        deploy:
            replicas: 2
            restart_policy:
                condition: any
networks:
    giveme5w1h-network:
        driver: overlay
