version: "3"
services:
    giveme5w1h-service:
        build: .
        image: giveme5w1h
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        ports:
            - 9099:9099
